# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aluno/Kagami

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aluno/Kagami

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluno/Kagami/CMakeFiles /home/aluno/Kagami/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluno/Kagami/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Kagami

# Build rule for target.
Kagami: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Kagami
.PHONY : Kagami

# fast build rule for target.
Kagami/fast:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/build
.PHONY : Kagami/fast

Entities/Component.o: Entities/Component.cpp.o
.PHONY : Entities/Component.o

# target to build an object file
Entities/Component.cpp.o:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Component.cpp.o
.PHONY : Entities/Component.cpp.o

Entities/Component.i: Entities/Component.cpp.i
.PHONY : Entities/Component.i

# target to preprocess a source file
Entities/Component.cpp.i:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Component.cpp.i
.PHONY : Entities/Component.cpp.i

Entities/Component.s: Entities/Component.cpp.s
.PHONY : Entities/Component.s

# target to generate assembly for a file
Entities/Component.cpp.s:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Component.cpp.s
.PHONY : Entities/Component.cpp.s

Entities/Entity.o: Entities/Entity.cpp.o
.PHONY : Entities/Entity.o

# target to build an object file
Entities/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Entity.cpp.o
.PHONY : Entities/Entity.cpp.o

Entities/Entity.i: Entities/Entity.cpp.i
.PHONY : Entities/Entity.i

# target to preprocess a source file
Entities/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Entity.cpp.i
.PHONY : Entities/Entity.cpp.i

Entities/Entity.s: Entities/Entity.cpp.s
.PHONY : Entities/Entity.s

# target to generate assembly for a file
Entities/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/Entities/Entity.cpp.s
.PHONY : Entities/Entity.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Kagami.dir/build.make CMakeFiles/Kagami.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Kagami"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Entities/Component.o"
	@echo "... Entities/Component.i"
	@echo "... Entities/Component.s"
	@echo "... Entities/Entity.o"
	@echo "... Entities/Entity.i"
	@echo "... Entities/Entity.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

